"""Fix relationships in Task and Comment

Revision ID: 3f1a309a6a82
Revises: 9fc6840907a5
Create Date: 2025-01-08 14:11:59.707465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f1a309a6a82'
down_revision: Union[str, None] = '9fc6840907a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
