"""Fix back_populates in Task and TaskStatus

Revision ID: 9fc6840907a5
Revises: 3a559a0147da
Create Date: 2025-01-08 14:10:34.517771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fc6840907a5'
down_revision: Union[str, None] = '3a559a0147da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
